export enum AuthErrorCode {
  INVALID_EMAIL_OR_PASSWORD = 0,
  EMAIL_ALREADY_EXISTS = 1,
  INVALID_EMAIL = 2,
  INVALID_PASSWORD = 3,
  INVALID_TOKEN = 4,
  USER_NOT_FOUND = 5,
  USER_NOT_VERIFIED = 6,
  USER_NOT_AUTHENTICATED = 7,
}
