export enum ErrorTypes {
  INTERNAL = 'interal',
  INVALID_OPERATION = 'invalid-operation',
  INVALID_PARAMETER = 'invalid-parameter',
  UNAUTHORIZED = 'unauthorized',
  FORBIDDEN = 'forbidden',
  CONFLICT = 'conflict',
  BAD_REQUEST = 'bad-request',
  NOT_FOUND = 'not-found',
  UNPROCESSABLE_ENTITY = 'unprocessable-entity',
  NOT_IMPLEMENTED = 'not-implemented',
  SERVICE_UNAVAILABLE = 'service-unavailable',
  GATEWAY_TIMEOUT = 'gateway-timeout',
  TOO_MANY_REQUESTS = 'too-many-requests',
  PAYLOAD_TOO_LARGE = 'payload-too-large',
  REQUEST_TIMEOUT = 'request-timeout',
  NETWORK_AUTHENTICATION_REQUIRED = 'network-authentication-required',
  NETWORK_READ_TIMEOUT = 'network-read-timeout',
  NETWORK_CONNECT_TIMEOUT = 'network-connect-timeout',
  NETWORK_ERROR = 'network-error',
  NETWORK_UNKNOWN_ERROR = 'network-unknown-error',
  NETWORK_SERVER_ERROR = 'network-server-error',
}
