export const ErrorTypes = {
  INTERNAL: 'INTERNAL',
  INVALID_OPERATION: 'INVALID_OPERATION',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
};
